#!/bin/bash
#
# Pretend Clang version is lower for CUDA
# Author: Adam Strzelecki
#
# Currently CUDA 7.5 supports Apple Clang up to 6.0, however latest Xcode
# contains version 6.1 or higher. This scripts pretends clang-version is 6.0,
# so CUDA can use it without complaining.

if [[ $# -eq 2 && "$1" == '-E' ]]; then
	/usr/bin/clang "$@" | sed -E \
		-e 's/__NV_CLANG_MAJOR__ .*/__NV_CLANG_MAJOR__ 8/' \
		-e 's/__NV_CLANG_MINOR__ .*/__NV_CLANG_MINOR__ 0/' \
		-e 's/__NV_CLANG_PATCH__ .*/__NV_CLANG_PATCH__ 0/'
	exit 0
fi

exec /usr/bin/clang "$@"
