#!/bin/bash
dir="$(dirname $0)/.."
find "$dir" \( \
		-iname '*.c'   -or \
		-iname '*.cpp' -or \
		-iname '*.cu'  -or \
		-iname '*.cuh' -or \
		-iname '*.h' \)    \
	\! -ipath "$dir/lib/*" \
	\! -ipath "$dir/doc/*" | \
xargs ${CLANG_FORMAT-clang-format} -style=file -i
